import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsArray,
  IsInt,
  IsISO8601,
  IsObject,
  IsOptional,
  IsString,
  Length,
  Matches,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

export class CreateReportDto {
  @ApiProperty({
    example: 'CSP-042',
    description: 'Local report number generated by the mobile app (CSP-### sequence).',
  })
  @IsString()
  @Matches(/^CSP-\d{1,6}$/)
  code!: string;

  @ApiPropertyOptional({ example: '1HGBH41JXMN109186', minLength: 17, maxLength: 17 })
  @IsOptional()
  @IsString()
  @Length(17, 17)
  @Matches(/^[A-HJ-NPR-Z0-9]{17}$/i)
  vin?: string;

  @ApiPropertyOptional({ example: 1834217, description: 'Expected file size in bytes (informational)' })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(50 * 1024 * 1024)
  sizeBytes?: number;

  @ApiPropertyOptional({
    example: '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    description: 'SHA-256 of the PDF, hex-encoded. Used for integrity verification.',
  })
  @IsOptional()
  @IsString()
  @Length(64, 64)
  @Matches(/^[a-f0-9]{64}$/i)
  hash?: string;

  @ApiPropertyOptional({ example: 'application/pdf', default: 'application/pdf' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  contentType?: string;

  @ApiPropertyOptional({ example: 'BMW', description: 'Vehicle make (display metadata for report history).' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  make?: string;

  @ApiPropertyOptional({ example: '320d', description: 'Vehicle model (display metadata for report history).' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  model?: string;

  @ApiPropertyOptional({
    example: '2026-06-03T10:00:00.000Z',
    description: 'When the inspection was performed (ISO 8601), distinct from upload time.',
  })
  @IsOptional()
  @IsISO8601()
  inspectedAt?: string;

  // --- website extension (all optional, additive — legacy clients ignore) ---

  @ApiPropertyOptional({
    example: 'ckqz2zk5e0000a8b8h4t8j2z3',
    description: 'Marketplace order this report fulfills (unique on Report).',
  })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  orderId?: string;

  @ApiPropertyOptional({ example: 87, minimum: 0, maximum: 100, description: 'Inspection quality score 0–100.' })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(100)
  qualityScore?: number;

  @ApiPropertyOptional({ example: 2018, minimum: 1900, maximum: 2100 })
  @IsOptional()
  @IsInt()
  @Min(1900)
  @Max(2100)
  year?: number;

  @ApiPropertyOptional({ example: 120000, minimum: 0, description: 'Mileage in kilometres.' })
  @IsOptional()
  @IsInt()
  @Min(0)
  mileageKm?: number;

  @ApiPropertyOptional({ example: 'Black' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  color?: string;

  @ApiPropertyOptional({ example: 'sedan' })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  bodyType?: string;

  @ApiPropertyOptional({ example: 'awd' })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  driveType?: string;

  @ApiPropertyOptional({
    type: 'object',
    additionalProperties: true,
    description: 'Structured inspection data (checklist, findings).',
  })
  @IsOptional()
  @IsObject()
  reportData?: Record<string, unknown>;

  @ApiPropertyOptional({
    type: 'array',
    items: { type: 'object' },
    description: 'Manifest of photos attached to this report.',
  })
  @IsOptional()
  @IsArray()
  photosManifest?: unknown[];
}
