import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsInt,
  IsISO8601,
  IsOptional,
  IsString,
  Length,
  Matches,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

export class CreateReportDto {
  @ApiProperty({
    example: 'CSP-042',
    description: 'Local report number generated by the mobile app (CSP-### sequence).',
  })
  @IsString()
  @Matches(/^CSP-\d{1,6}$/)
  code!: string;

  @ApiPropertyOptional({ example: '1HGBH41JXMN109186', minLength: 17, maxLength: 17 })
  @IsOptional()
  @IsString()
  @Length(17, 17)
  @Matches(/^[A-HJ-NPR-Z0-9]{17}$/i)
  vin?: string;

  @ApiPropertyOptional({ example: 1834217, description: 'Expected file size in bytes (informational)' })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(50 * 1024 * 1024)
  sizeBytes?: number;

  @ApiPropertyOptional({
    example: '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    description: 'SHA-256 of the PDF, hex-encoded. Used for integrity verification.',
  })
  @IsOptional()
  @IsString()
  @Length(64, 64)
  @Matches(/^[a-f0-9]{64}$/i)
  hash?: string;

  @ApiPropertyOptional({ example: 'application/pdf', default: 'application/pdf' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  contentType?: string;

  @ApiPropertyOptional({ example: 'BMW', description: 'Vehicle make (display metadata for report history).' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  make?: string;

  @ApiPropertyOptional({ example: '320d', description: 'Vehicle model (display metadata for report history).' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  model?: string;

  @ApiPropertyOptional({
    example: '2026-06-03T10:00:00.000Z',
    description: 'When the inspection was performed (ISO 8601), distinct from upload time.',
  })
  @IsOptional()
  @IsISO8601()
  inspectedAt?: string;
}
