/**
 * Merges the machine-translated catalog sidecars into the canonical catalog.
 *
 * The four human-translated locales (de/en/ru/uk) are authored directly in
 * `catalog.data.ts`. The other 26 the mobile app ships are generated by
 * `carsalepro-mobile/tool/l10n/` and land here as one JSON file per locale:
 *
 *   src/catalog/i18n/catalog.<tag>.json
 *     { "parts.door_fl": "Porte avant gauche",
 *       "angles.front.hint": "...", ... }
 *
 * Keys are `<collection>.<entryId>` for a label and `<collection>.<entryId>.hint`
 * for an angle hint — the same identifiers the mobile extractor emits, so the
 * round trip is checkable rather than conventional.
 *
 * A sidecar naming an entry that does not exist is reported, never fatal: the
 * catalog is allowed to drop an entry between a translation run and an export,
 * and failing the export would block a legitimate change.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { CatalogV1, LocalizedLabel } from './catalog.data';

export const I18N_DIR = resolve(__dirname, 'i18n');

/** `catalog.zh-Hant.json` -> `zh-Hant`. */
const TAG_FROM_FILE = /^catalog\.([A-Za-z]{2}(?:-[A-Za-z]{4})?)\.json$/;

export interface MergeReport {
  /** Locale tags found on disk, in load order. */
  tags: string[];
  /** How many label/hint values each tag contributed. */
  applied: Record<string, number>;
  /** Sidecar keys that matched no catalog entry, per tag. */
  orphans: Record<string, string[]>;
}

type LabelIndex = Map<string, LocalizedLabel>;

/**
 * Builds `"<collection>.<id>" -> label` and `"<collection>.<id>.hint" -> hint`
 * over every collection that carries localized text.
 */
function indexLabels(catalog: CatalogV1): LabelIndex {
  const index: LabelIndex = new Map();

  const add = (key: string, label: LocalizedLabel | undefined): void => {
    if (label) index.set(key, label);
  };

  for (const a of catalog.angles) {
    add(`angles.${a.id}`, a.label);
    add(`angles.${a.id}.hint`, a.hint);
  }
  // Miss a collection here and its labels never merge: the sidecar keys become
  // orphans, which is a warning rather than an error, and every locale silently
  // falls back to English while the export still reports success.
  for (const g of catalog.groups) add(`groups.${g.id}`, g.label);
  for (const s of catalog.subgroups) add(`subgroups.${s.id}`, s.label);
  for (const p of catalog.parts) add(`parts.${p.id}`, p.label);
  for (const t of catalog.damageTypes) add(`damageTypes.${t.id}`, t.label);
  for (const m of catalog.repairMethods) add(`repairMethods.${m.id}`, m.label);
  for (const c of catalog.kstCodes) add(`kstCodes.${c.code}`, c.label);
  for (const i of catalog.checklist) add(`checklist.${i.number}`, i.label);
  for (const p of catalog.thicknessPanels) add(`thicknessPanels.${p.id}`, p.label);

  return index;
}

/**
 * Applies every sidecar in [dir] to [catalog] **in place** and returns what
 * happened. Mutating in place is deliberate: `CATALOG_V1` is a module
 * singleton that the controller serves and the exporter writes, and handing
 * back a deep clone would let the two drift.
 */
export function mergeCatalogI18n(
  catalog: CatalogV1,
  dir: string = I18N_DIR,
): MergeReport {
  const report: MergeReport = { tags: [], applied: {}, orphans: {} };
  if (!existsSync(dir)) return report;

  const index = indexLabels(catalog);

  const files = readdirSync(dir)
    .filter((f) => TAG_FROM_FILE.test(f))
    .sort();

  for (const file of files) {
    const tag = TAG_FROM_FILE.exec(file)![1];
    const raw = JSON.parse(readFileSync(join(dir, file), 'utf8')) as Record<
      string,
      unknown
    >;

    let applied = 0;
    const orphans: string[] = [];

    for (const [key, value] of Object.entries(raw)) {
      if (typeof value !== 'string' || value.length === 0) continue;
      const label = index.get(key);
      if (!label) {
        orphans.push(key);
        continue;
      }
      label[tag] = value;
      applied++;
    }

    report.tags.push(tag);
    report.applied[tag] = applied;
    if (orphans.length) report.orphans[tag] = orphans.sort();
  }

  return report;
}
