import { Body, Controller, Get, HttpCode, Post } from '@nestjs/common';
import { ApiHeader, ApiOkResponse, ApiOperation, ApiTags } from '@nestjs/swagger';
import { DeviceId } from '../common/decorators/device-id.decorator';
import { QuotaDto } from './dto/quota.dto';
import { UpgradeDto } from './dto/upgrade.dto';
import { QuotaService } from './quota.service';

@ApiTags('quota')
@ApiHeader({
  name: 'X-Device-Id',
  required: true,
  description: 'UUID v4 generated by the mobile client. Persistent per install.',
})
@Controller('quota')
export class QuotaController {
  constructor(private readonly quotaService: QuotaService) {}

  @Get()
  @ApiOperation({ summary: 'Get current quota status for the device' })
  @ApiOkResponse({ type: QuotaDto })
  async get(@DeviceId() deviceId: string): Promise<QuotaDto> {
    const quota = await this.quotaService.getOrInit(deviceId);
    return this.quotaService.toDto(quota);
  }

  @Post('upgrade')
  @HttpCode(200)
  @ApiOperation({
    summary: 'Mark device as PRO after IAP success',
    description:
      'MVP: trusts client-side IAP validation. Persists isPro=true and platform. ' +
      'Phase 2 will perform server-side receipt validation against App Store / Play.',
  })
  @ApiOkResponse({ type: QuotaDto })
  async upgrade(@DeviceId() deviceId: string, @Body() dto: UpgradeDto): Promise<QuotaDto> {
    const quota = await this.quotaService.markPro(deviceId, dto.platform, dto.receipt);
    return this.quotaService.toDto(quota);
  }
}
