import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsISO8601,
  IsLatitude,
  IsLongitude,
  IsOptional,
  IsString,
  Length,
  Matches,
  MaxLength,
} from 'class-validator';
import { Transform } from 'class-transformer';

export class QuoteOrderDto {
  @ApiProperty({ example: 52.52 })
  @IsLatitude()
  lat!: number;

  @ApiProperty({ example: 13.405 })
  @IsLongitude()
  lng!: number;

  @ApiProperty({ example: '2026-07-01T09:00:00.000Z' })
  @IsISO8601()
  scheduledAt!: string;
}

export class CreateOrderDto {
  @ApiPropertyOptional({ example: '1HGBH41JXMN109186', minLength: 17, maxLength: 17 })
  @IsOptional()
  @IsString()
  @Length(17, 17)
  @Matches(/^[A-HJ-NPR-Z0-9]{17}$/i)
  vin?: string;

  @ApiProperty({ example: 'BMW' })
  @IsString()
  @MaxLength(64)
  make!: string;

  @ApiProperty({ example: '320d' })
  @IsString()
  @MaxLength(64)
  model!: string;

  @ApiPropertyOptional({ example: 'https://mobile.de/listing/123' })
  @IsOptional()
  @IsString()
  @MaxLength(2048)
  listingUrl?: string;

  @ApiProperty({ example: 'Musterstraße 1, 10115 Berlin' })
  @IsString()
  @MaxLength(240)
  address!: string;

  @ApiProperty({ example: 52.52 })
  @IsLatitude()
  lat!: number;

  @ApiProperty({ example: 13.405 })
  @IsLongitude()
  lng!: number;

  @ApiProperty({ example: '2026-07-01T09:00:00.000Z' })
  @IsISO8601()
  scheduledAt!: string;
}

/** Statuses an assigned inspector may push the order into via /status. */
export enum InspectorStatusUpdate {
  EN_ROUTE = 'EN_ROUTE',
  IN_PROGRESS = 'IN_PROGRESS',
}

export class UpdateOrderStatusDto {
  @ApiProperty({ enum: InspectorStatusUpdate })
  @IsEnum(InspectorStatusUpdate)
  status!: InspectorStatusUpdate;
}

const REPORT_CODE_PATTERN =
  /^CSP-(\d{1,12}|[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$/i;

/**
 * Trim only — NEVER upper-case.
 *
 * The mobile app mints `CSP-` + a LOWER-CASE uuid v4
 * (`carsalepro-mobile/lib/core/utils/report_code.dart`) and `Report.code` is
 * matched literally in Postgres, so upper-casing here turned every genuine
 * modern Report ID into a 404 on the attach path — the same code answered 200
 * from the public preview endpoint and 404 here. `REPORT_CODE_PATTERN` already
 * carries the `/i` flag, so validation is unaffected.
 *
 * `src/public/dto/report-lookup.dto.ts` (trim) and
 * `src/listings/dto/create-listing.dto.ts` (no transform at all) were already
 * correct; this DTO was the outlier.
 */
const normalizeReportCode = ({ value }: { value: unknown }) =>
  typeof value === 'string' ? value.trim() : value;

export class AttachOrderReportDto {
  @ApiProperty({
    example: 'CSP-67e5a3d2-9c41-4b7e-8f2a-1d3c5e7a9b0f',
    description: 'Report code generated by the mobile inspection app.',
  })
  @Transform(normalizeReportCode)
  @IsString()
  @MaxLength(48)
  @Matches(REPORT_CODE_PATTERN, { message: 'code must be a CSP report code' })
  code!: string;
}

export class DisputeOrderDto {
  @ApiProperty({ example: 'Inspector never showed up' })
  @IsString()
  @MaxLength(1000)
  reason!: string;
}

export enum OrderRole {
  customer = 'customer',
  inspector = 'inspector',
}

export class ListOrdersQueryDto {
  @ApiPropertyOptional({ enum: OrderRole, default: OrderRole.customer })
  @IsOptional()
  @IsEnum(OrderRole)
  role?: OrderRole;

  @ApiPropertyOptional({ example: 'PAID' })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  status?: string;
}
