import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsBoolean,
  IsEnum,
  IsISO8601,
  IsLatitude,
  IsLongitude,
  IsNotEmpty,
  IsOptional,
  IsString,
  Length,
  Matches,
  MaxLength,
} from 'class-validator';
import { Transform } from 'class-transformer';

export class QuoteOrderDto {
  @ApiProperty({ example: 52.52 })
  @IsLatitude()
  lat!: number;

  @ApiProperty({ example: 13.405 })
  @IsLongitude()
  lng!: number;

  /**
   * DEPRECATED (DEN-290). The customer no longer chooses a time, and the price
   * does not depend on one. Accepted only so a website deployed before that
   * change does not get a 400. Do not send it from new code.
   */
  @ApiPropertyOptional({ example: '2026-07-01T09:00:00.000Z', deprecated: true })
  @IsOptional()
  @IsISO8601()
  scheduledAt?: string;
}

export class CreateOrderDto {
  @ApiPropertyOptional({ example: '1HGBH41JXMN109186', minLength: 17, maxLength: 17 })
  @IsOptional()
  @IsString()
  @Length(17, 17)
  @Matches(/^[A-HJ-NPR-Z0-9]{17}$/i)
  vin?: string;

  @ApiProperty({ example: 'BMW' })
  @IsString()
  @MaxLength(64)
  make!: string;

  @ApiProperty({ example: '320d' })
  @IsString()
  @MaxLength(64)
  model!: string;

  /**
   * The seller's phone number OR a link to the listing, as free text (DEN-116).
   * Required since DEN-291: the assigned inspector must contact the car owner
   * before the trip, and this is the only channel the order carries. The name
   * stayed `listingUrl` so the wire contract did not change.
   */
  @ApiProperty({ example: '+4930123456 or https://mobile.de/listing/123' })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  @IsString()
  @IsNotEmpty()
  @MaxLength(2048)
  listingUrl!: string;

  @ApiProperty({ example: 'Musterstraße 1, 10115 Berlin' })
  @IsString()
  @MaxLength(240)
  address!: string;

  @ApiProperty({ example: 52.52 })
  @IsLatitude()
  lat!: number;

  @ApiProperty({ example: 13.405 })
  @IsLongitude()
  lng!: number;

  /**
   * DEPRECATED (DEN-290). The customer no longer chooses a time, and the price
   * does not depend on one. Accepted only so a website deployed before that
   * change does not get a 400. Do not send it from new code.
   */
  @ApiPropertyOptional({ example: '2026-07-01T09:00:00.000Z', deprecated: true })
  @IsOptional()
  @IsISO8601()
  scheduledAt?: string;
}

/** Statuses an assigned inspector may push the order into via /status. */
export enum InspectorStatusUpdate {
  EN_ROUTE = 'EN_ROUTE',
  IN_PROGRESS = 'IN_PROGRESS',
}

export class UpdateOrderStatusDto {
  @ApiProperty({ enum: InspectorStatusUpdate })
  @IsEnum(InspectorStatusUpdate)
  status!: InspectorStatusUpdate;
}

/**
 * DEN-291. The result of the assigned inspector's call to the car owner.
 * `true` unlocks the trip. `false` cancels the order with a full refund.
 */
export class OwnerContactDto {
  @ApiProperty({ example: true })
  @IsBoolean()
  reached!: boolean;
}

const REPORT_CODE_PATTERN =
  /^CSP-(\d{1,12}|[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$/i;

/**
 * Trim only — NEVER upper-case.
 *
 * The mobile app mints `CSP-` + a LOWER-CASE uuid v4
 * (`carsalepro-mobile/lib/core/utils/report_code.dart`) and `Report.code` is
 * matched literally in Postgres, so upper-casing here turned every genuine
 * modern Report ID into a 404 on the attach path — the same code answered 200
 * from the public preview endpoint and 404 here. `REPORT_CODE_PATTERN` already
 * carries the `/i` flag, so validation is unaffected.
 *
 * `src/public/dto/report-lookup.dto.ts` (trim) and
 * `src/listings/dto/create-listing.dto.ts` (no transform at all) were already
 * correct; this DTO was the outlier.
 */
const normalizeReportCode = ({ value }: { value: unknown }) =>
  typeof value === 'string' ? value.trim() : value;

export class AttachOrderReportDto {
  @ApiProperty({
    example: 'CSP-67e5a3d2-9c41-4b7e-8f2a-1d3c5e7a9b0f',
    description: 'Report code generated by the mobile inspection app.',
  })
  @Transform(normalizeReportCode)
  @IsString()
  @MaxLength(48)
  @Matches(REPORT_CODE_PATTERN, { message: 'code must be a CSP report code' })
  code!: string;
}

export class DisputeOrderDto {
  @ApiProperty({ example: 'Inspector never showed up' })
  @IsString()
  @MaxLength(1000)
  reason!: string;
}

/**
 * The reason an inspector must give to hand an accepted order back.
 *
 * The reason is NOT optional and NOT allowed to be blank: the customer reads it
 * in the cancellation letter, and "the inspector cancelled, no reason given" is
 * the answer that makes them call support. `Transform` trims first, so a body of
 * spaces fails `Length` instead of passing as text.
 */
export class DeclineOrderDto {
  @ApiProperty({ example: 'My van broke down and I cannot reach the address today' })
  @IsString()
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  @Length(3, 1000)
  reason!: string;
}

export enum OrderRole {
  customer = 'customer',
  inspector = 'inspector',
}

export class ListOrdersQueryDto {
  @ApiPropertyOptional({ enum: OrderRole, default: OrderRole.customer })
  @IsOptional()
  @IsEnum(OrderRole)
  role?: OrderRole;

  @ApiPropertyOptional({ example: 'PAID' })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  status?: string;
}
