import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  Param,
  Post,
} from '@nestjs/common';
import {
  ApiHeader,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';
import { DeviceId } from '../common/decorators/device-id.decorator';
import { ErrorResponseDto } from '../common/dto/error-response.dto';
import { CreateReportDto } from './dto/create-report.dto';
import {
  CompleteReportResponseDto,
  CreateReportResponseDto,
  ReportListDto,
} from './dto/report-response.dto';
import { ReportsService } from './reports.service';

@ApiTags('reports')
@ApiHeader({
  name: 'X-Device-Id',
  required: true,
  description: 'UUID v4 generated by the mobile client. Persistent per install.',
})
@Controller('reports')
export class ReportsController {
  constructor(private readonly reportsService: ReportsService) {}

  @Post()
  @ApiOperation({
    summary: 'Reserve a report and obtain a presigned R2 upload URL',
    description:
      'Atomically checks the FREE-tier quota (3 reports lifetime). PRO devices have no limit. ' +
      'On quota exhaustion returns 402 Payment Required and does NOT create a report row.',
  })
  @ApiOkResponse({ type: CreateReportResponseDto })
  @ApiResponse({ status: 402, type: ErrorResponseDto, description: 'FREE-tier limit reached' })
  async create(
    @DeviceId() deviceId: string,
    @Body() dto: CreateReportDto,
  ): Promise<CreateReportResponseDto> {
    return this.reportsService.create(deviceId, dto);
  }

  @Post(':id/complete')
  @HttpCode(200)
  @ApiOperation({
    summary: 'Confirm the PDF was successfully uploaded to R2',
    description:
      'Verifies the object exists in R2 and marks the report as uploaded. ' +
      'Reports that never complete remain in the device history but cannot be downloaded.',
  })
  @ApiParam({ name: 'id' })
  @ApiOkResponse({ type: CompleteReportResponseDto })
  async complete(
    @DeviceId() deviceId: string,
    @Param('id') id: string,
  ): Promise<CompleteReportResponseDto> {
    return this.reportsService.complete(deviceId, id);
  }

  @Get()
  @ApiOperation({ summary: 'List all reports for the device (history)' })
  @ApiOkResponse({ type: ReportListDto })
  async list(@DeviceId() deviceId: string): Promise<ReportListDto> {
    return this.reportsService.list(deviceId);
  }

  @Delete(':id')
  @ApiOperation({ summary: 'Soft-delete a report and remove the PDF from R2' })
  @ApiParam({ name: 'id' })
  @ApiOkResponse({ schema: { example: { id: 'ckqz...', deleted: true } } })
  async remove(
    @DeviceId() deviceId: string,
    @Param('id') id: string,
  ): Promise<{ id: string; deleted: true }> {
    return this.reportsService.remove(deviceId, id);
  }
}
