import { Controller, HttpCode, Post } from '@nestjs/common';
import { ApiHeader, ApiOkResponse, ApiOperation, ApiTags } from '@nestjs/swagger';
import { DeviceId } from '../common/decorators/device-id.decorator';
import { LinkCodeResponseDto } from './dto/link-code-response.dto';
import { LinkCodesService } from './link-codes.service';

@ApiTags('link-codes')
@ApiHeader({
  name: 'X-Device-Id',
  required: true,
  description: 'UUID v4 generated by the mobile client. Persistent per install.',
})
@Controller('link-codes')
export class LinkCodesController {
  constructor(private readonly linkCodes: LinkCodesService) {}

  @Post()
  @HttpCode(201)
  @ApiOperation({
    summary: 'Generate a 6-digit link code for the current device',
    description:
      'The user enters this code in the website cabinet to attach the mobile device ' +
      '(and its report archive) to their account. Single-use, valid for 10 minutes.',
  })
  @ApiOkResponse({ type: LinkCodeResponseDto })
  async create(@DeviceId() deviceId: string): Promise<LinkCodeResponseDto> {
    const { code, expiresAt } = await this.linkCodes.generate(deviceId);
    return { code, expiresAt: expiresAt.toISOString() };
  }
}
